---
- name: Create GitLab Project Group
  become: true
  community.general.gitlab_group:
    api_url: "{{ provision_gitlab_gitlab_url }}"
    validate_certs: "{{ provision_gitlab_validate_certs }}"
    api_token: "{{ provision_gitlab_access_token }}"
    name: "{{ provision_gitlab_group_name }}"
    visibility: internal
    state: present

- name: Configure Gitlab Gravatar
  uri:
    url: "{{ provision_gitlab_gitlab_url }}/api/v4/application/settings?gravatar_enabled={{ provision_gitlab_gravatar_enabled }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ provision_gitlab_access_token }}"
    validate_certs: "{{ provision_gitlab_validate_certs }}"
