---
# Source: cert-manager/charts/cainjector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: "cert-manager"
  labels:
    app: cainjector
    chart: cainjector-v0.8.1
    release: cert-manager
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cainjector
      release: cert-manager
  template:
    metadata:
      labels:
        app: cainjector
        release: cert-manager
      annotations:
    spec:
      serviceAccountName: cert-manager-cainjector
      containers:
        - name: cainjector
          image: "harbor.lab.int/rancher/quay.io/jetstack/cert-manager-cainjector:v0.8.1"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --leader-election-namespace=$(POD_NAMESPACE)
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}
