---
#active_directory_domain:
active_directory_user_base: "OU=Users,OU=Rancher,DC=lab,DC=int"

#ssh_ad_fqdn: 
ssh_ad_ou_to_join: "OU=Computers,OU=Rancher,DC=lab,DC=int"

hostname_active_directory_fqdn: "{{ active_directory_domain }}"

ssh_allow_groups:
  - 'rancher-users'
  - 'rancher-admins'

ssh_sudo_groups:
  - 'rancher-admins'
