---
environment_name: dev
organizational_unit_name: "Rancher"
dc_location: PTM
deploy_rke_keepalived: true

# The location on the build server to copy the certs from.
cert_from_ca_dc_root_key_path: /var/tmp/rancher_certs

# The path to the CA cert to install for the bdellegrazie.ca_certificate playbook
#ca_certificates_local_dir: /var/tmp/rancher_certs

ca_certificates_update: true

# The intermediary cert & key to use
cert_from_ca_intermediate_cert_pem: certs/rancher-intermediate.cert.pem
cert_from_ca_intermediate_key_pem: private/rancher-intermediate.key.pem

# Trusted CA certificates to use
ca_certificates_trusted:
  - name: Rancher_Dev_Root_CA
    pem: "{{ lookup('file', '{{ cert_from_ca_dc_root_key_path }}/rancher-ca.cert.pem') | trim }}"

# CA cert for Ranchers certificates
rke_ca_certificates_trusted: "{{ ca_certificates_trusted }}"

cert_from_ca_chain_cert_pem: rancher-ca.cert.pem
