---
harbor_cluster_floating_ip: "192.168.146.104"
harbor_hostname: harbor.lab.int

harbor_ldap_url: "ldap://192.168.142.2"
harbor_ldap_search_dn: "CN=SA-RN-HARBOR,OU=Service_Accounts,OU=rancher,DC=lab,DC=int"
harbor_ldap_base_dn: "OU=Users,OU=Rancher,DC=lab,DC=int"
harbor_ldap_filter: "(objectClass=person)"
harbor_ldap_group_base_dn: "CN=rancher-harbor-admins,OU=Groups,OU=Rancher,DC=lab,DC=int"
harbor_ldap_group_search_filter: "(objectClass=group)"
harbor_ldap_group_admin_dn: "CN=rancher-harbor-admins,OU=Groups,OU=Rancher,DC=lab,DC=int"

harbor_self_signed_cert: true
harbor_ssl_certificate: "{{ harbor_certs_path }}/harbor.lab.int.cert.full.chain.pem"
harbor_ssl_enabled: true
harbor_ssl_private_key: "{{ harbor_certs_path }}/private/harbor.lab.int.key.pem"
harbor_ssl_ca_chain_cert: "{{ harbor_certs_path }}/rancher-ca-chain.cert.pem"

harbor_validate_certs: no
