---
#rke_password:
rancher_url: rancher-ef6cb8c94223eee0.elb.eu-west-1.amazonaws.com

#rke_admin_username: admin
#rke_username: "{{ rke_admin_username }}"
rancher_telemetry: out

#rke_vcenter_username:
#rke_vcenter_password: 

rancher_apps_cluster_name: apps-cluster
apps_cluster_worker_nodes: 1

apps_cluster_ingress_options:
  hsts: True
  hsts-include-subdomains: False
  proxy-buffer-size: 128k
  proxy-buffers-number: "4"

apps_cluster_ingress_extra_args:
  default-ssl-certificate: "ingress-nginx/ingress-default-cert"

apps_cluster_control_plane_vsphere_tags: []
apps_cluster_etcd_vsphere_tags: []
apps_cluster_worker_vsphere_tags: []

deploy_rancher_ui_tls_path: /etc/ssl
rancher_management_kubernetes_version: v1.19.6-rancher1-1
rke_clone_from: "{{ rke_datacenter }}/vm/Templates/Ubuntu-18.04-CIS-vmware-rancher-v02"
rke_cluster_config_rancher_kubernetes_engine_config_private_registries:
  - url: "harbor.lab.int/{{ harbor_repo_path }}"
    isDefault: true
    user: registry_user
rke_cluster_config_rancher_kubernetes_engine_config_kubernetes_version: v1.19.6-rancher1-1
apps_cluster_datastore: "{{ rke_datacenter }}/datastore/vsanDatastore"

configure_rancher: yes
