---
redis_version: 6.0.6
redis_port: 6379
redis_bind: "{{ ansible_default_ipv4.address }} 127.0.0.1"
redis_sentinel_bind: "{{ ansible_default_ipv4.address }} 127.0.0.1"
redis_logfile: "/var/log/redis.log"
redis_sentinel_port: 26379
redis_sentinel_logfile: "/var/log/redis_sentinel.log"
redis_sentinal_cluster_name: master01

sentinel_facts_redis_sentinel_port: "{{ redis_sentinel_port }}"
sentinel_facts_redis_sentinel_password: "{{ redis_sentinel_password }}"
sentinel_facts_cluster_name: "{{ redis_sentinal_cluster_name }}"