- name: Ensure certs dir exists
  become: yes
  file:
    path: "{{ lets_encrypt_certs_path }}"
    state: directory
  register: certdir

- name: Create RSA key to be used for account creation
  become: yes
  openssl_privatekey:
    path: "{{ lets_encrypt_rsa_account_key_path }}"
    size: 4096
    type: RSA

- name: Create RSA key to be used for certificate
  become: yes
  openssl_privatekey:
    path: "{{ lets_encrypt_rsa_private_key_path }}"
    size: 4096
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request
  become: yes
  openssl_csr:
    path: "{{ lets_encrypt_csr_path }}"
    privatekey_path: "{{ lets_encrypt_rsa_private_key_path }}"
    common_name: "{{ lets_encrypt_domain }}"

- name: Create a challenge using an account key file.
  become: yes
  acme_certificate:
    acme_version: 2
    acme_directory: "{{ lets_encrypt_acme_directory }}"
    terms_agreed: "yes"
    account_key_src: "{{ lets_encrypt_rsa_account_key_path }}"
    csr: "{{ lets_encrypt_csr_path }}"
    dest: "{{ lets_encrypt_crt_dest }}"
    fullchain_dest: "{{ lets_encrypt_fullchain_dest }}"
  register: lets_encrypt_challenge

- name: Register challenge data
  delegate_to: localhost
  route53:
    zone: "{{ lets_encrypt_r53_zone }}"
    record: "{{ lets_encrypt_challenge.challenge_data[lets_encrypt_domain]['dns-01'].record }}"
    type: TXT
    ttl: 60
    state: present
    wait: yes
    value: "{{ lets_encrypt_challenge.challenge_data[lets_encrypt_domain]['dns-01'].resource_value | regex_replace('^(.*)$', '\"\\1\"') }}"
    overwrite: yes
  when: lets_encrypt_challenge is changed and lets_encrypt_domain in lets_encrypt_challenge.challenge_data

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  become: yes
  acme_certificate:
    acme_version: 2
    acme_directory: "{{ lets_encrypt_acme_directory }}"
    account_key_src: "{{ lets_encrypt_rsa_account_key_path }}"
    account_email: "{{ lets_encrypt_cert_email }}"
    src: "{{ lets_encrypt_csr_path }}"
    cert: "{{ lets_encrypt_crt_dest }}"
    fullchain: "{{ lets_encrypt_fullchain_dest }}"
    chain: "{{ lets_encrypt_chain_dest }}"
    challenge: dns-01
    remaining_days: 60
    data: "{{ lets_encrypt_challenge }}"
  when: lets_encrypt_challenge is changed
